### ISSUE TITLE
[NumberGuesser] Object initializer

### ISSUE THREAD

**Issue by pavel-b-novikov** [WildWind03/nsudotnet#1]
```offensiveComments[1] =```
А переделайте, пожалуйста, на человеческий object initializer. Смотреть страшно

**Comment by WildWind03** [comment]
У меня набор offensive comments зависит от имени. Я не могу использовать object initializer

**Comment by pavel-b-novikov** [comment]
А что именно мешает? Необходимость создать массив до того, как вы узнаете имя пользователя?

**Comment by WildWind03** [comment]
Да, действительно, ничего не мешает

**Comment by WildWind03** [comment]
Исправил
