### ISSUE TITLE
[Enigma] Чтение из файла (2)

### ISSUE THREAD

**Issue by pavel-b-novikov** [WildWind03/nsudotnet#11]
```var keyLengthInString = (int) ((float) key.Length / (key.Length + iv.Length) * keyAndIvString.Length);```

Слушайте, а мне прям нравится на какие извращения вы идете вместо использования TextReader-a и ReadLine

Давайте вы все же перепишете чтобы не позориться

**Comment by WildWind03** [comment]
Исправил

**Comment by pavel-b-novikov** [comment]
```if (null == keyString || null == ivString)``` 

А как же проверка строк на пустоту? Вдруг кто-то запишет в файл просто переносы строки

**Comment by WildWind03** [comment]
Если кто-то запишет в файл пустые строки, то при декодирование кинется исключение о неверном размере ключа/iv (а я его в нужное время поймаю и выведу сообщение). Или вы хотите, чтобы я игнорировал переносы строк?

**Comment by pavel-b-novikov** [comment]
нет, я хочу чтобы вы познали мощь string.IsNullOrEmpty, ибо как это стандарт для подобных вещей

**Comment by WildWind03** [comment]
Ок, теперь вместо явной проверки на null использую IsNullOrEmpty
