### ISSUE TITLE
[Enigma] Путь к файлу с ключом

### ISSUE THREAD

**Issue by pavel-b-novikov** [WildWind03/nsudotnet#13]
```outputFilename.LastIndexOf(".", StringComparison.Ordinal)```

Я вроде говорил на лекции чтобы ничего подобного не писали. Разве нет?

**Comment by WildWind03** [comment]
Сменил способ получения позиции, с которой начинается расширение, а также Concat заменил на Insert

**Comment by pavel-b-novikov** [comment]
(facepalm) 
Я не это имел в виду

**Comment by WildWind03** [comment]
А что в имели в виду? Я посмотрел, как формируют путь к файлу остальные ребята. Кто-то риплейсит .txt на .key.txt (и в случаях, если файл имеет имя filename.txt.txt, это будет работать неверно), кто-то добавляет .key после .txt и вообще не парится, что это противоречит ТЗ.

**Comment by pavel-b-novikov** [comment]
А нормальный способ оперировать с путями в .NET тем временем один

**Comment by WildWind03** [comment]
Исправил на Path.ChangeExtension
