### ISSUE TITLE
[JsonSerializer] Строка 122

### ISSUE THREAD

**Issue by pavel-b-novikov** [WildWind03/nsudotnet#6]
```jsonEnumerableString = jsonEnumerableString.Substring(0, jsonEnumerableString.Length - 1);```

Вот она. Пожалуйста поясните, какие проблемы в контексте остального кода вы здесь видите? Потом переделайте. И больше никогда так не делайте.

**Comment by WildWind03** [comment]
Всю работу с билдером я поправил. Теперь последнюю запятую я убираю с помощью Replace у самого билдера, не создавая лишних объектов ни в substring, ни при конкатенации

**Comment by pavel-b-novikov** [comment]
На что только люди ни идут чтобы только избежать решения "просто не писать эту запятую". Но да ладно.
