### ISSUE TITLE
[JsonSerializer] Append

### ISSUE THREAD

**Issue by pavel-b-novikov** [WildWind03/nsudotnet#7]
```jsonDictionaryBuilder.Append(Concat("\"", i, "\":", ToJson(value), ","));```

Вам даже решарпер не подсказал использовать AppendFormat?

**Comment by WildWind03** [comment]
Да, решарпер не подсказал. Исправил.

**Comment by pavel-b-novikov** [comment]
Вы передаете в формат константную строку одним из аргументов? Да вы не понимаете смысл .Format!

**Comment by WildWind03** [comment]
Исправил.
