### ISSUE TITLE
[JsonSerializer] StringBuilder

### ISSUE THREAD

**Issue by pavel-b-novikov** [WildWind03/nsudotnet#8]
```return serializedObjects + "}";```

Странно.. из предыдущих строк я так понял что вы знаете как пользоваться StringBuilder-ом. А из этой вижу что не знаете

**Comment by WildWind03** [comment]
Но ведь в этой строчке не будет создано ни одного временного лишнего объекта, зачем использовать билдер?

**Comment by pavel-b-novikov** [comment]
Это как вы дошли до такой мысли?

**Comment by WildWind03** [comment]
У меня есть 2 строчки, я их конкатенирую и получаю третью строчку, которую собственно и возвращаю. В случае с билдером у меня бы тоже были бы первые 2 строчки, которые бы я положил в билдер, и тоже была бы 3 строчка, которую я бы на выходе из билдера получил.

**Comment by pavel-b-novikov** [comment]
Чушь пишете.
Нет, у вас был билдер, который внутри себя держит превосходный динамический буфер. Вместо того чтобы дописать в него интернированную строку, вы весь этот буфер превращаете в строку. Для чего? А чтобы на следующем шаге создать её полную копию с добавленной скобочкой. Молодец.

**Comment by WildWind03** [comment]
Да, конечно, я согласен. Я просто отвечал в именно в контексте тех двух строк, не обращая внимания на то, что serializedObject получен из билдера, и имел в виду, что не смысла использовать билдер при конкатенации 2 строк

**Comment by pavel-b-novikov** [comment]
Ну я не даром упомянул предыдущие строки.

Переделывайте

**Comment by WildWind03** [comment]
Переделал
